-- CreateTable
CREATE TABLE "manishaAddData" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "DataId" STRING NOT NULL,
    "fullName" STRING,
    "address" STRING,
    "phone" STRING,

    CONSTRAINT "manishaAddData_pkey" PRIMARY KEY ("id")
);
